### ISSUE TITLE
Support RFC-2616 Host header host/port combination

### ISSUE THREAD

**Issue by rezan** [gquintard/libvmod-gwist#1]
Please see https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23

It could be possible to do this in VCL, but that will introduce more error surface error and will be a hurdle for users.

**Comment by rezan** [comment]
IPv6 support too: https://www.ietf.org/rfc/rfc2732.txt

**Comment by gquintard** [comment]
@rezan : can you look at PR #3 ?

**Comment by gquintard** [comment]
Fixed by #3
