### ISSUE TITLE
Backends always expire, even if used

### ISSUE THREAD

**Issue by sesse** [gquintard/libvmod-gwist#6]
Hi,

It seems that when a backend is reused (within TTL), be->tod (time-of-death?) is not updated. This means that if you ask for a backend with e.g. TTL 60 seconds, a new one will be created for the next request after 60 seconds no matter what, meaning that there will be multiple backends for the same host lingering around. Is this really the intention? Can't just the backend be reused forever until nothing else wants it?

**Comment by gquintard** [comment]
Hi,

Actually, that's on purpose, i the sense that gwist is super minimalist and revalidation is a tricky subject. However, I have a bigger, better, and more general purpose version in the work that should satisfy you.

In the mean time, can I direct you to https://github.com/Dridi/libvmod-named that should do what you need, with the added benefits of round-robining on the resolved hosts.

**Comment by sesse** [comment]
So it is about DNS revalidation? In my case, I always just give in 127.0.0.1 (or ::1), so it shouldn't really matter, but I see it's harder in the general case.

libvmod-named doesn't do dynamic backends as far as I can tell, so it doesn't really fill the same need.

**Comment by gquintard** [comment]
It is indeed about DNS revalidation. If you only ever use local addresses, why do you need gwist?

named does dynamic backends :-)

**Comment by sesse** [comment]
Because I need a different backend per vhost (even though they all go to the same Apache instance), so that they don't reuse HTTP connections across vhosts :-) It's a bit complicated, but has to do with requirements of the backend. (The current solution relies on patching Varnish and gwist.)
